export const DataTable = [
    {
        vm_name: "AlphaBI_NFSstorage_246",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 4,
        vm_memory: 8192,
        vm_memory_beauty: "8G",
        vm_disk_size: 310,
        vm_disk_size_beauty: "310G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 7,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.246\n" +
            "nic3: 10.31.6.246",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },{
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },{
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
    {
        vm_name: "BettaBI_NFSstorage_247",
        vm_comment: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_description: "Сервер файлового хранилища NFS для AlphaBI (прод)",
        vm_cpu: 8,
        vm_memory: 4096,
        vm_memory_beauty: "4G",
        vm_disk_size: 520,
        vm_disk_size_beauty: "520G",
        vm_os_distribution: "CentOS Linux",
        vm_os_family: "Linux",
        vm_os_version: 8,
        vm_os_codename: "",
        vm_nics: "nic2: 10.76.241.247\n" +
            "nic3: 10.31.6.247",
        System: "AlphaBI",
        Owner: "БАРС_ГРУП",
        Priority: 4,
        report_date: "06.09.2023 15:28:52"
    },
]